### ISSUE TITLE
Graphics shaders leak memory

### ISSUE THREAD

**Issue by mundusnine** [tizilogic/krink#3]
I use krink in a hot-reloading situation(i.e. I hot-reload krink). There's currently a leak in the [Vulkan backend](https://github.com/Kode/Kinc/issues/790) but even if the vulkan code would work, [kr_g2_destroy](https://github.com/tizilogic/krink/blob/main/Sources/krink/graphics2/graphics.c#L86) doesn't call the destroy funcs  of for pipelines,vertexbuffers and inderbuffers for each shader: isp,csp,tsp and sdf.

**Comment by tcdude** [comment]
Thanks. I added the necessary destroy calls in there to fix that (once Kinc also behaves as expected ofc).. feel free to reopen the issue if this doesn't fix the problem though.
